#!/bin/bash
python3 -c "print((lambda w,s:(lambda n:n.translate(str.maketrans('01234567','bestchol')))(format(int(w.translate(str.maketrans('water','01234')),5)+int(s.translate(str.maketrans('stir.','01234')),5),'o')))(\"$WATER\",\"$STIR\"))"
